let TOURS=[];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(url,opt={}){const r=await fetch(url,{headers:{'Content-Type':'application/json',...(opt.headers||{})},...opt});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||'Request failed');return d}
async function loadTours(){const d=await api('/api/tours');TOURS=d.tours||[];renderTours()}
function renderTours(){const el=document.querySelector('#tourGrid');if(!el)return;el.innerHTML=TOURS.map(t=>`<article class="tour-card"><div class="tour-image"><img src="${esc(t.image)}" alt="${esc(t.title)}"><span>${esc(t.category)}</span></div><div class="tour-body"><div class="tour-date">📅 ${esc(t.date)} · ${esc(t.duration)}</div><h3>${esc(t.title)}</h3><p>${esc(t.desc)}</p><div class="tour-bottom"><strong>${t.price?`৳${Number(t.price).toLocaleString('bn-BD')}`:'কাস্টম মূল্য'} <small>${t.price?'জনপ্রতি':''}</small></strong><button class="btn btn-primary book-btn" data-id="${esc(t.id)}">Book Now</button></div></div></article>`).join('')}
function openBooking(id){const t=TOURS.find(x=>x.id===id);if(!t)return;document.querySelector('#bookingTour').value=t.id;document.querySelector('#bookingTourName').textContent=t.title;document.querySelector('#bookingModal').classList.add('show');document.body.classList.add('modal-open')}
function closeBooking(){document.querySelectorAll('.modal').forEach(x=>x.classList.remove('show'));document.body.classList.remove('modal-open')}
document.addEventListener('click',e=>{const b=e.target.closest('.book-btn');if(b)openBooking(b.dataset.id);if(e.target.closest('[data-close]'))closeBooking()});
document.addEventListener('DOMContentLoaded',async()=>{await loadTours();const form=document.querySelector('#bookingForm');form?.addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(form);const tourName=document.querySelector('#bookingTourName')?.textContent||fd.get('tour')||'';const name=String(fd.get('name')||'').trim();const phone=String(fd.get('phone')||'').trim();const date=String(fd.get('date')||'').trim();const travellers=Number(fd.get('travellers')||1);const message=String(fd.get('message')||'').trim();if(!name||!phone||!date||travellers<1){alert('সব প্রয়োজনীয় তথ্য সঠিকভাবে দিন।');return}const waText=`নতুন Booking Request — Narsingdi Travel Group\n\nপ্যাকেজ: ${tourName}\nনাম: ${name}\nমোবাইল: ${phone}\nভ্রমণের তারিখ: ${date}\nযাত্রী সংখ্যা: ${travellers}\nঅতিরিক্ত তথ্য: ${message||'নেই'}`;try{const d=await api('/api/bookings',{method:'POST',body:JSON.stringify({tour:fd.get('tour'),name,phone,date,travellers,message})});const text=waText+`\n\nBooking ID: ${d.bookingId}`;window.location.href='https://wa.me/8801621425718?text='+encodeURIComponent(text)}catch(err){window.location.href='https://wa.me/8801621425718?text='+encodeURIComponent(waText)}});const y=document.querySelector('#year');if(y)y.textContent=new Date().getFullYear()}).catch(e=>console.error(e));
